project:
  type: website
  output-dir: docs

website:
  title: "les_reports"
  navbar:
    left:
      - href: index.html
        text: Home
      - may.qmd
      - august.qmd
      - june.qmd
      - november.qmd
      - october.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

