---
title: "CV June Agathe"
format: html
---

```{r}

#Install libraries
# install.packages(c("pacman", "tidyverse", "rio"))

#load libraries
library(tidyverse)
library(sf)
library(gstat)
library(sp)


data <- read.table(file = "data/Data_Example_1.txt", header = TRUE, sep = "\t")
data$sampleID <- as.numeric(data$sampleID)
data$subplot <- as.numeric(data$subplot)
data$OTU_all_taxa <- as.numeric(data$OTU_all_taxa)

# Créer des sous-ensembles de données pour June
june <- data[data$month == "June", ]

# Spécifier les colonnes x et y comme coordonnées
coordinates(june) <- ~x + y

# Calculer le variogramme empirique pour novembre
var1 <- variogram((log(OTU_all_taxa) * 10) ~ 1, locations = june, cutoff = 8, width = 1)

# Ajuster le modèle de variogramme
mod1 <- fit.variogram(var1, vgm(psill = NA, "Exp", range = NA, 1), fit.sills = TRUE, fit.ranges = TRUE, fit.method = 1)

mod1
```

```{r}

# Validation croisée pour évaluer la précision du modèle
cv <- krige.cv((log(OTU_all_taxa) * 10) ~ 1, locations = june, model = mod1, nfold = nrow(june)) # cv : Corss validation

cv

cv_df <- as.data.frame(cv)

rio::export(cv_df, "docs/cv_agathe", format = "csv")

cv_df

```

```{r}
#Creons une fonction pour calculer l'erreur moyenne

EM <- function(effectif, zcore){
  sum(zcore)/effectif
}

EM(nrow(cv), zcore = cv$zscore)

```
